"""initial schema"""

revision = '63da3c25624b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('platform_hint', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_cases'))
    )
    op.create_index('ix_cases_source_type_created_at', 'cases', ['source_type', 'created_at'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index('ix_scans_platform_created_at', 'scans', ['platform', 'created_at'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('seller_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('account_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_hash', sa.String(length=128), nullable=True),
    sa.Column('messenger_hash', sa.String(length=128), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_observations'))
    )
    op.create_index(op.f('ix_seller_observations_account_hash'), 'seller_observations', ['account_hash'], unique=False)
    op.create_index(op.f('ix_seller_observations_messenger_hash'), 'seller_observations', ['messenger_hash'], unique=False)
    op.create_index(op.f('ix_seller_observations_phone_hash'), 'seller_observations', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_seller_observations_platform'), 'seller_observations', ['platform'], unique=False)
    op.create_index('ix_seller_observations_platform_seller_id', 'seller_observations', ['platform', 'seller_id'], unique=False)
    op.create_index(op.f('ix_seller_observations_seller_id'), 'seller_observations', ['seller_id'], unique=False)
    op.create_table('case_chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('embedding', VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_case_chunks_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_case_chunks')),
    sa.UniqueConstraint('case_id', 'chunk_order', name='uq_case_chunks_case_id_chunk_order')
    )
    op.create_index(op.f('ix_case_chunks_case_id'), 'case_chunks', ['case_id'], unique=False)
    op.create_table('case_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_value_raw', sa.Text(), nullable=True),
    sa.Column('entity_value_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_case_entities_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_entities'))
    )
    op.create_index(op.f('ix_case_entities_case_id'), 'case_entities', ['case_id'], unique=False)
    op.create_index('ix_case_entities_case_id_entity_type', 'case_entities', ['case_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_case_entities_entity_value_hash'), 'case_entities', ['entity_value_hash'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('fk_feedback_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_scan_id'), 'feedback', ['scan_id'], unique=False)
    op.create_table('scan_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('fk_scan_blocks_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_blocks')),
    sa.UniqueConstraint('scan_id', 'block_id', name='uq_scan_blocks_scan_id_block_id')
    )
    op.create_index(op.f('ix_scan_blocks_scan_id'), 'scan_blocks', ['scan_id'], unique=False)
    op.create_table('scan_evidence_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.CheckConstraint('end_offset >= start_offset', name=op.f('ck_scan_evidence_items_end_offset_after_start_offset')),
    sa.CheckConstraint('start_offset >= 0', name=op.f('ck_scan_evidence_items_start_offset_non_negative')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('fk_scan_evidence_items_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_evidence_items'))
    )
    op.create_index(op.f('ix_scan_evidence_items_scan_id'), 'scan_evidence_items', ['scan_id'], unique=False)
    op.create_table('scan_similar_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_scan_similar_cases_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['case_chunks.chunk_id'], name=op.f('fk_scan_similar_cases_chunk_id_case_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('fk_scan_similar_cases_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_similar_cases')),
    sa.UniqueConstraint('scan_id', 'rank', name='uq_scan_similar_cases_scan_id_rank')
    )
    op.create_index(op.f('ix_scan_similar_cases_case_id'), 'scan_similar_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_scan_similar_cases_chunk_id'), 'scan_similar_cases', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_scan_similar_cases_scan_id'), 'scan_similar_cases', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_similar_cases_scan_id'), table_name='scan_similar_cases')
    op.drop_index(op.f('ix_scan_similar_cases_chunk_id'), table_name='scan_similar_cases')
    op.drop_index(op.f('ix_scan_similar_cases_case_id'), table_name='scan_similar_cases')
    op.drop_table('scan_similar_cases')
    op.drop_index(op.f('ix_scan_evidence_items_scan_id'), table_name='scan_evidence_items')
    op.drop_table('scan_evidence_items')
    op.drop_index(op.f('ix_scan_blocks_scan_id'), table_name='scan_blocks')
    op.drop_table('scan_blocks')
    op.drop_index(op.f('ix_feedback_scan_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_case_entities_entity_value_hash'), table_name='case_entities')
    op.drop_index('ix_case_entities_case_id_entity_type', table_name='case_entities')
    op.drop_index(op.f('ix_case_entities_case_id'), table_name='case_entities')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_case_chunks_case_id'), table_name='case_chunks')
    op.drop_table('case_chunks')
    op.drop_index(op.f('ix_seller_observations_seller_id'), table_name='seller_observations')
    op.drop_index('ix_seller_observations_platform_seller_id', table_name='seller_observations')
    op.drop_index(op.f('ix_seller_observations_platform'), table_name='seller_observations')
    op.drop_index(op.f('ix_seller_observations_phone_hash'), table_name='seller_observations')
    op.drop_index(op.f('ix_seller_observations_messenger_hash'), table_name='seller_observations')
    op.drop_index(op.f('ix_seller_observations_account_hash'), table_name='seller_observations')
    op.drop_table('seller_observations')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index('ix_scans_platform_created_at', table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_cases_source_type_created_at', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
