"""add scan rag score fields

Revision ID: 7a2f6c8d9e10
Revises: e9b2a7c4d6f1
Create Date: 2026-06-07 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "7a2f6c8d9e10"
down_revision: str | None = "e9b2a7c4d6f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add deterministic score metadata generated by RAG scan analysis."""
    op.add_column("scans", sa.Column("risk_points", sa.Integer(), nullable=True))
    op.add_column(
        "scans",
        sa.Column("risk_score_breakdown_json", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )


def downgrade() -> None:
    """Remove deterministic score metadata."""
    op.drop_column("scans", "risk_score_breakdown_json")
    op.drop_column("scans", "risk_points")
